### PR TITLE
Do not require attributes.

### PR DESCRIPTION
**Pull request by seanabrahams**
Why: Humans make mistakes and sometimes URLs will not include expected OG info.

For example, https://www.k1speed.com/ does not include `og:type`, which is a required attribute, and thus caused crawling to fail even though it has `og:title`, `og:description`, `og:url`, and `og:image`. This removes required attributes and will allow access to the information that is available.

### CODE REVIEW

**Comment by seanabrahams** [comment]
I admit this may cause issues for people relying on `OGP::MissingAttributeError`. No worries if you'd rather not merge this.

**Comment by dvisockas** [comment]
Or maybe `OGP::OpenGraph` class could have an optional argument called `required_attributes` so one could explicitly pass an empty array in your case or it would default to current implementation.

What do you think? @jcouture

**Comment by berkes** [comment]
IMO, it sould be up to the consumer to validate the OG tags. But the lib should have a method to determine validity.

Instead of removing the `check_required_attributes` entirely, why not make it public and rename to `valid?`. Removing from the initializer as well.

That way the consumer can say:

```
open_graph = OGP::OpenGraph.new(response.body)
if open_graph.valid?
   build_fancy_card(open_graph)
else
   build_empty_card
end
```

**Comment by seanabrahams** [comment]
Closing in favor of https://github.com/jcouture/ogp/pull/8

**Pull request closed without merging**
